package com.cpyt.entity;
// Generated 10/11/2018 02:25:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer idPago;
     private TipoPago tipoPago;
     private Usuario usuario;
     private Venta venta;
     private BigDecimal montoPagado;
     private Date fechaPago;
     private String nroBoucherOpera;
     private int isDeleted;

    public Pago() {
    }

	
    public Pago(TipoPago tipoPago, Usuario usuario, Venta venta, BigDecimal montoPagado, Date fechaPago, int isDeleted) {
        this.tipoPago = tipoPago;
        this.usuario = usuario;
        this.venta = venta;
        this.montoPagado = montoPagado;
        this.fechaPago = fechaPago;
        this.isDeleted = isDeleted;
    }
    public Pago(TipoPago tipoPago, Usuario usuario, Venta venta, BigDecimal montoPagado, Date fechaPago, String nroBoucherOpera, int isDeleted) {
       this.tipoPago = tipoPago;
       this.usuario = usuario;
       this.venta = venta;
       this.montoPagado = montoPagado;
       this.fechaPago = fechaPago;
       this.nroBoucherOpera = nroBoucherOpera;
       this.isDeleted = isDeleted;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getNroBoucherOpera() {
        return this.nroBoucherOpera;
    }
    
    public void setNroBoucherOpera(String nroBoucherOpera) {
        this.nroBoucherOpera = nroBoucherOpera;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }




}


