package com.cpyt.entity;
// Generated 06/11/2018 04:24:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private TipoPersona tipoPersona;
     private String dniRuc;
     private String razonNombres;
     private String direccion;
     private String celular;
     private Date fechaNacimiento;
     private int isDeleted;
     private Set ventasForIdReferencia = new HashSet(0);
     private Set ventasForIdCliente = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Persona() {
    }

	
    public Persona(TipoPersona tipoPersona, String dniRuc, String razonNombres, String direccion, String celular, Date fechaNacimiento, int isDeleted) {
        this.tipoPersona = tipoPersona;
        this.dniRuc = dniRuc;
        this.razonNombres = razonNombres;
        this.direccion = direccion;
        this.celular = celular;
        this.fechaNacimiento = fechaNacimiento;
        this.isDeleted = isDeleted;
    }
    public Persona(TipoPersona tipoPersona, String dniRuc, String razonNombres, String direccion, String celular, Date fechaNacimiento, int isDeleted, Set ventasForIdReferencia, Set ventasForIdCliente, Set usuarios) {
       this.tipoPersona = tipoPersona;
       this.dniRuc = dniRuc;
       this.razonNombres = razonNombres;
       this.direccion = direccion;
       this.celular = celular;
       this.fechaNacimiento = fechaNacimiento;
       this.isDeleted = isDeleted;
       this.ventasForIdReferencia = ventasForIdReferencia;
       this.ventasForIdCliente = ventasForIdCliente;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public TipoPersona getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public String getDniRuc() {
        return this.dniRuc;
    }
    
    public void setDniRuc(String dniRuc) {
        this.dniRuc = dniRuc;
    }
    public String getRazonNombres() {
        return this.razonNombres;
    }
    
    public void setRazonNombres(String razonNombres) {
        this.razonNombres = razonNombres;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getVentasForIdReferencia() {
        return this.ventasForIdReferencia;
    }
    
    public void setVentasForIdReferencia(Set ventasForIdReferencia) {
        this.ventasForIdReferencia = ventasForIdReferencia;
    }
    public Set getVentasForIdCliente() {
        return this.ventasForIdCliente;
    }
    
    public void setVentasForIdCliente(Set ventasForIdCliente) {
        this.ventasForIdCliente = ventasForIdCliente;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


