package com.cpyt.entity;
// Generated 06/11/2018 04:24:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SerieComprobante generated by hbm2java
 */
public class SerieComprobante  implements java.io.Serializable {


     private Integer idSerieComprobante;
     private TipoComprobante tipoComprobante;
     private String serie;
     private int iniciarNumeracion;
     private int isDeleted;
     private Set ventas = new HashSet(0);

    public SerieComprobante() {
    }

	
    public SerieComprobante(TipoComprobante tipoComprobante, String serie, int iniciarNumeracion, int isDeleted) {
        this.tipoComprobante = tipoComprobante;
        this.serie = serie;
        this.iniciarNumeracion = iniciarNumeracion;
        this.isDeleted = isDeleted;
    }
    public SerieComprobante(TipoComprobante tipoComprobante, String serie, int iniciarNumeracion, int isDeleted, Set ventas) {
       this.tipoComprobante = tipoComprobante;
       this.serie = serie;
       this.iniciarNumeracion = iniciarNumeracion;
       this.isDeleted = isDeleted;
       this.ventas = ventas;
    }
   
    public Integer getIdSerieComprobante() {
        return this.idSerieComprobante;
    }
    
    public void setIdSerieComprobante(Integer idSerieComprobante) {
        this.idSerieComprobante = idSerieComprobante;
    }
    public TipoComprobante getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(TipoComprobante tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public int getIniciarNumeracion() {
        return this.iniciarNumeracion;
    }
    
    public void setIniciarNumeracion(int iniciarNumeracion) {
        this.iniciarNumeracion = iniciarNumeracion;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


