package com.cpyt.entity;
// Generated 06/11/2018 04:24:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoComprobante generated by hbm2java
 */
public class TipoComprobante  implements java.io.Serializable {


     private Integer idTipoComprobante;
     private String nombre;
     private Set ventas = new HashSet(0);
     private Set serieComprobantes = new HashSet(0);

    public TipoComprobante() {
    }

	
    public TipoComprobante(String nombre) {
        this.nombre = nombre;
    }
    public TipoComprobante(String nombre, Set ventas, Set serieComprobantes) {
       this.nombre = nombre;
       this.ventas = ventas;
       this.serieComprobantes = serieComprobantes;
    }
   
    public Integer getIdTipoComprobante() {
        return this.idTipoComprobante;
    }
    
    public void setIdTipoComprobante(Integer idTipoComprobante) {
        this.idTipoComprobante = idTipoComprobante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getSerieComprobantes() {
        return this.serieComprobantes;
    }
    
    public void setSerieComprobantes(Set serieComprobantes) {
        this.serieComprobantes = serieComprobantes;
    }




}


