package com.cpyt.entity;
// Generated 06/11/2018 04:24:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer idUnidadMedida;
     private String abreviado;
     private String nombre;
     private int isDeleted;
     private Set productos = new HashSet(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(String abreviado, String nombre, int isDeleted) {
        this.abreviado = abreviado;
        this.nombre = nombre;
        this.isDeleted = isDeleted;
    }
    public UnidadMedida(String abreviado, String nombre, int isDeleted, Set productos) {
       this.abreviado = abreviado;
       this.nombre = nombre;
       this.isDeleted = isDeleted;
       this.productos = productos;
    }
   
    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }
    public String getAbreviado() {
        return this.abreviado;
    }
    
    public void setAbreviado(String abreviado) {
        this.abreviado = abreviado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


