package com.cpyt.entity;
// Generated 10/11/2018 02:25:12 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VentaDetalle generated by hbm2java
 */
public class VentaDetalle  implements java.io.Serializable {


     private Integer idVentaDetalle;
     private Producto producto;
     private Venta venta;
     private int cantidad;
     private BigDecimal precioUnitario;
     private BigDecimal total;
     private int entregado;
     private Date fechaEntrega;

    public VentaDetalle() {
    }

	
    public VentaDetalle(Producto producto, Venta venta, int cantidad, BigDecimal precioUnitario, BigDecimal total, int entregado) {
        this.producto = producto;
        this.venta = venta;
        this.cantidad = cantidad;
        this.precioUnitario = precioUnitario;
        this.total = total;
        this.entregado = entregado;
    }
    public VentaDetalle(Producto producto, Venta venta, int cantidad, BigDecimal precioUnitario, BigDecimal total, int entregado, Date fechaEntrega) {
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.total = total;
       this.entregado = entregado;
       this.fechaEntrega = fechaEntrega;
    }
   
    public Integer getIdVentaDetalle() {
        return this.idVentaDetalle;
    }
    
    public void setIdVentaDetalle(Integer idVentaDetalle) {
        this.idVentaDetalle = idVentaDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(BigDecimal precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public int getEntregado() {
        return this.entregado;
    }
    
    public void setEntregado(int entregado) {
        this.entregado = entregado;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }




}


